export enum Theme {
    GRAO_ARABICA = "GRAO_ARABICA",
    GRAO_ROBUSTA = "GRAO_ROBUSTA",

    TORRA_CLARA = "TORRA_CLARA",
    TORRA_MEDIA = "TORRA_MEDIA",
    TORRA_ESCURA = "TORRA_ESCURA",

    METODO_PRENSA = "METODO_PRENSA",
    METODO_SYPHON = "METODO_SYPHON",
    METODO_HARIO = "METODO_HARIO",

    TIPOS_TORRA = "TIPOS_TORRA", 
    METODO_PREPARO = "METODO_PREPARO",
    TIPOS_GRAOS = "TIPOS_GRAOS",
}